### PR TITLE
Added support for several mods

### PR DESCRIPTION
**Pull request by eberkain**
VSR, RLA, USI, HGR, BDynamics, QuizTech

### CODE REVIEW

**Comment by eberkain** [comment]
Added some more,  All combined this adds support for the following. 

Vens Stock Revamp
RLA
QuizTech
BDynamics
Home Grown Rockets
USI
Mk2 Expansion
Mk3 Expansion
Mk2.5 Spaceplane
MOLE

**Comment by eberkain** [comment]
fixed some stuff I missed. :)

**Comment by Kerbas-ad-astra** [comment]
The "NEEDS" blocks aren't necessary -- if (for example) QuizTech isn't installed, there will be no Mk2_LinAerospike part for Module Manager to patch.

**Comment by linuxgurugamer** [comment]
True, but they won't hurt.
Thanks for this, I'll be merging it.  Are you planning on any others, if so, I'll hold off on a release until you get another PR.

**Comment by eberkain** [comment]
Not planning on it.  I ended up dropping this and engine igniter for my playthrough.  Was just more realism than I wanted to deal with.  :)

**Pull request merged**
